version: '3.8'

services:
  sk08-web:
    container_name: sk08-web
    build:
      context: ./backend
    image: jansodomka/wea_semestralni_prace:backend
    ports:
      - "8007:8007"
    volumes:
      - ./backend:/app
      - /home/cerny/logs/sk08-web:/app/logs
    environment:
      - DATABASE_URL=postgresql://user:password@sk08-db/mydatabase
      - PYTHONPATH=/app
      - FLASK_ENV=development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - cdb-network

  frontend:
    build:
      context: ./frontend
    image: jansodomka/wea_semestralni_prace:frontend
    ports:
      - "3007:3007"
    depends_on:
      - sk08-web
    networks:
      - internal

  db:
    container_name: sk08-db
    hostname: sk08-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "50007:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  sql-client:
    image: adminer
    restart: always
    ports:
      - "10007:8080"
    depends_on:
      - db
    networks:
      - internal

networks:
  cdb-network:
    name: cdb-network
    driver: bridge
    external: true
  internal:
    driver: bridge